# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/exposedbuckle48/Documents/Semester_5/DSD/Lab_9/XADC/Basys-3-XADC.srcs/sources_1/ip/xadc_wiz_2/xadc_wiz_2.xci
# IP: The module: 'xadc_wiz_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/exposedbuckle48/Documents/Semester_5/DSD/Lab_9/XADC/Basys-3-XADC.srcs/sources_1/ip/xadc_wiz_2/xadc_wiz_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_wiz_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/exposedbuckle48/Documents/Semester_5/DSD/Lab_9/XADC/Basys-3-XADC.srcs/sources_1/ip/xadc_wiz_2/xadc_wiz_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_wiz_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/exposedbuckle48/Documents/Semester_5/DSD/Lab_9/XADC/Basys-3-XADC.srcs/sources_1/ip/xadc_wiz_2/xadc_wiz_2.xci
# IP: The module: 'xadc_wiz_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/exposedbuckle48/Documents/Semester_5/DSD/Lab_9/XADC/Basys-3-XADC.srcs/sources_1/ip/xadc_wiz_2/xadc_wiz_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_wiz_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/exposedbuckle48/Documents/Semester_5/DSD/Lab_9/XADC/Basys-3-XADC.srcs/sources_1/ip/xadc_wiz_2/xadc_wiz_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_wiz_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
