webtalk_init -webtalk_dir /home/exposedbuckle48/Documents/Semester_5/DSD/Lab_1/Project_1/Project_1.sim/sim_1/behav/xsim/xsim.dir/simpleNAND_testbench_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Sep 11 15:59:23 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2288692" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "380d4588-55be-4a51-8396-b30cebc4ecc2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "92f1622ecd3344aba4a826a30b7bdc80" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "unknown" -context "user_environment"
webtalk_add_data -client project -key os_release -value "unknown" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2832.499 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "124648_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4230816099 -regid "" -xml /home/exposedbuckle48/Documents/Semester_5/DSD/Lab_1/Project_1/Project_1.sim/sim_1/behav/xsim/xsim.dir/simpleNAND_testbench_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/exposedbuckle48/Documents/Semester_5/DSD/Lab_1/Project_1/Project_1.sim/sim_1/behav/xsim/xsim.dir/simpleNAND_testbench_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/exposedbuckle48/Documents/Semester_5/DSD/Lab_1/Project_1/Project_1.sim/sim_1/behav/xsim/xsim.dir/simpleNAND_testbench_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
